"""spec_versions

Revision ID: 9f4c6fa90381
Revises: 075df8a64554
Create Date: 2026-07-08 08:46:28.848318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9f4c6fa90381"
down_revision: Union[str, Sequence[str], None] = "075df8a64554"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spec_versions",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("spec_id", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["spec_versions.version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
    )
    op.create_index(
        "ix_spec_versions_pipeline_seq", "spec_versions", ["pipeline_id", "seq"], unique=False
    )
    op.create_index(op.f("ix_spec_versions_spec_id"), "spec_versions", ["spec_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spec_versions_spec_id"), table_name="spec_versions")
    op.drop_index("ix_spec_versions_pipeline_seq", table_name="spec_versions")
    op.drop_table("spec_versions")
    # ### end Alembic commands ###
