"""spec_versions_add-uniquekey

Revision ID: d5b07061b01e
Revises: 9f4c6fa90381
Create Date: 2026-07-08 09:18:13.798222

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5b07061b01e"
down_revision: Union[str, Sequence[str], None] = "9f4c6fa90381"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_spec_versions_pipeline_parent", "spec_versions", ["pipeline_id", "parent_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_spec_versions_pipeline_parent", "spec_versions", type_="unique")
    # ### end Alembic commands ###
